### ISSUE TITLE
custom.css.scss has a typo

### ISSUE THREAD

**Issue by MyklClason** [vtt01uk/Commit2it#1]
While reviewing your code for inspiration on mine, I noticed a [typo in Line #75](https://github.com/vtt01uk/Commit2it/blob/master/app/assets/stylesheets/custom.css.scss#L75)

```
marging-top: 45px;
```

Should be 

```
margin-top: 45px;
```

I was gonna make a pull request, but that's going to change your layout and may not be what you want. So went the issues route instead.

**Comment by vtt01uk** [comment]
Thanks; I've made the amendment.
